### ISSUE TITLE
新手恳请了解如何根据你的pdnsd makefile给LEDE编译pdnsd

### ISSUE THREAD

**Issue by tacuar** [AlexZhuo/luci-app-shadowsocksR#10]
Alex你好,

可以请教下根据你的pdnsd makefile给LEDE特定平台编译一个ipk的方法流程吗.
比如我现在目录是 lede-sdk
然后接下去 git clone  ..............
然后....
或者需要make menuconfig
最后 make package/  ............

本人小白, 恳请大神指导!

**Comment by AlexZhuo** [comment]
看这篇教程：http://blog.csdn.net/lvshaorong/article/details/52931211

**Comment by tacuar** [comment]
谢谢指导!!!!!! 
另外LEDE现在sdk都转为musl了, 导致现在编译ipk出错误,不知道如何解决

**Comment by AlexZhuo** [comment]
我编译LEDE没有问题啊
