### ISSUE TITLE
使用GFWList模式无法翻墙！非大陆IP模式，全局都是好使的！

### ISSUE THREAD

**Issue by 81pla** [AlexZhuo/luci-app-shadowsocksR#11]
使用GFWList模式无法翻墙！非大陆IP模式，全局都是好使的！
http://www.right.com.cn/forum/thread-198649-1-1.html
已经参照这个设置过pdnsd
电脑DNS已经清空

就是翻不出去

**Comment by AlexZhuo** [comment]
你的DNS服务器地址必须设置成路由器的地址，另外确保你的dnsmasq是full版本
