### ISSUE TITLE
最新版的lede主干，make menuconfig的时候，在菜单中就找不到shadowsocksR的选项

### ISSUE THREAD

**Issue by f8q8** [AlexZhuo/luci-app-shadowsocksR#39]
最新版的lede主干，make menuconfig的时候，在菜单中就找不到shadowsocksR的选项

**Comment by Aslin-Ameng** [comment]
在NetWork -> LuCI -> luci-app-shadowsocksR里面

**Comment by f8q8** [comment]
里面也没有啊

**Comment by f8q8** [comment]
用openwrt的18.0.6版本编译，好像是在NetWork -> LuCI -> luci-app-shadowsocksR里面和application中都看不到

**Comment by Aslin-Ameng** [comment]
我忘了 我把Alex老大的 luci-app-shadowsocksR里面的makefile改了 我改为

define Package/$(PKG_NAME)
  SECTION:=luci
  CATEGORY:=LuCI
  SUBMENU:=3. Applications
  TITLE:=luci for shadowsocksR
  PKGARCH:=all
  DEPENDS:=+shadowsocksr-libev +dnsforwarder +ipset +ip +iptables-mod-tproxy +kmod-ipt-tproxy +iptables-mod-nat-extra +coreutils +coreutils-nohup +dnsmasq-full +wget
endef

你照着我这个直接替换就行了 然后就看见了

**Comment by f8q8** [comment]
可以了，谢谢
